[book]
authors = ["David Wong"]
language = "en"
multilingual = false
src = "src"
title = "Mina Protocol"

[preprocessor.katex]

[output.html]
curly-quotes = true
git-repository-url = "https://www.github.com/o1-labs/mina-book"
