name: Deploy to Github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: set up rust (for cache)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: set up cache for rust
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: |
          cargo install mdbook
          cargo install mdbook-katex
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
